site_name: Computational Thinking and Programming - Laboratory
site_url: ""
edit_uri: ""
use_directory_urls: false
extra_css: [extra.css]
extra_javascript: 
  - extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
    name: mkdocs
    nav_style: light

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: index.md  
  - Labs:
    - 1. Lists, Tuples, and Dictionaries: chapter/05.md
    - 2. Random numbers: chapter/04.md    
    - 3. Searching and Sorting: chapter/06.md
    - 4. Recursion: chapter/07.md